############################
# Global configuration
############################
global(
    maxMessageSize="8k"
)

############################
# Modules
############################
module(load="imudp")
module(load="imtcp")

input(type="imudp" port="514")
input(type="imtcp" port="514")

############################
# Log everything to file + stdout for debugging
############################
template(name="RawLog" type="string"
    string="%timereported:::date-rfc3339% [%fromhost-ip%] %rawmsg%\n")

# Write to file
*.* action(type="omfile" file="/var/log/nat-incoming.log" template="RawLog")
